# Generated by Django 5.0.1 on 2024-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reteta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('timp', models.CharField(max_length=50)),
                ('dificultate', models.CharField(max_length=20)),
                ('ingrediente', models.TextField()),
            ],
        ),
    ]
